//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameVariables
{
	/// <summary>
	/// The texture of the floor
	/// </summary>
	public static Texture2D FloorTexture;
    
    /// <summary>
    /// The texture of the exit
    /// </summary>
    public static Texture2D ExitTexture;

    /// <summary>
    /// The texture of the wall
    /// </summary>
    public static Dictionary<string, Texture2D> WallTextures;

    /// <summary>
	/// The size of tiles in the game
	/// </summary>
	public static int TileSize = 32;

    /// <summary>
    /// The texture of the torch
    /// </summary>
    public static Texture2D TorchTexture;

	/// <summary>
	/// The texture of the player being Idle
	/// </summary>
	public static Texture2D PlayerIdleTexture;

	/// <summary>
	/// The texture of the minotuar
	/// </summary>
	public static Texture2D MinotuarTexture;

	/// <summary>
	/// The texture of the comrade being Idle
	/// </summary>
	public static Texture2D ComradeIdleTexture;

	/// <summary>
	/// The radius of the torch's light
	/// </summary>
	public static int TorchLightRadius;

	/// <summary>
	/// The basic font of the game
	/// </summary>
	public static SpriteFont BasicFont;

	/// <summary>
	/// The speed of the player
	/// </summary>
	public static int PlayerSpeed;

	/// <summary>
	/// The speed of the minotuar's movement
	/// </summary>
	public static int MinotuarSpeed;

	/// <summary>
	/// Texture of the comrade being picked up
	/// </summary>
	public static Texture2D ComradePickupTexture;

	/// <summary>
	/// The texture of the player moving
	/// </summary>
	public static Texture2D PlayerMovingTexture;

	/// <summary>
	/// The texture of the player picking up a comrade
	/// </summary>
	public static Texture2D PlayerPickupTexture;

    /// <summary>
    /// The texture of the Play menu button
    /// </summary>
    public static Texture2D MenuPlayButtonTexture;

    public static Texture2D MenuStopButtonTexture;

    public static Texture2D MenuTitleTexture;

    public static Texture2D PauseDeclareTexture;

    /// <summary>
    /// Loads the textures of the game
    /// </summary>
    public static void LoadTextures(ContentManager content)
    {
        // Load the floor, exit and walls of the maze
            FloorTexture = content.Load<Texture2D>("MazeTiles/floor");
            ExitTexture = content.Load<Texture2D>("MazeTiles/exit");
            string[] wallTypes = new string[] { "TTTT", "TTTF", "TTFT", "TTFF", "TFTT", "TFFT", "TFTF", "TFFF", "FFFF", "FTTT", "FTTF", "FTFT", "FFTT", "FFFT", "FFTF", "FTFF" };
            WallTextures = new Dictionary<string, Texture2D>();
            foreach (string wallType in wallTypes)
                WallTextures.Add(wallType, content.Load<Texture2D>("MazeTiles/wall-" + wallType));

        // Load the characters' texture
            PlayerIdleTexture = content.Load<Texture2D>("Characters/player sprite");
        MinotuarTexture = content.Load<Texture2D>("Characters/minotaur");
        ComradeIdleTexture = content.Load<Texture2D>("Characters/comrade");
        TorchTexture = content.Load<Texture2D>("Characters/torch");


        //Load menu textures
        MenuPlayButtonTexture = content.Load<Texture2D>("Menu/playButton");
        MenuStopButtonTexture = content.Load<Texture2D>("Menu/stopButton");
        MenuTitleTexture = content.Load<Texture2D>("Menu/menuTitle");

        PauseDeclareTexture = content.Load<Texture2D>("Menu/pauseDeclare");
    }

}

