//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The minotaur that trys to kill the player
/// </summary>
public class Minotaur : MoveableTile, AnimatedTile, Movable
{
	/// <summary>
	/// Move the minotuar by the given speed in the given directional axis (true = left + right, false = up + down)
	/// </summary>
	public virtual void Move(GameTime() gameTime, int speed, bool dir)
	{
		throw new System.NotImplementedException();
	}

	/// <summary>
	/// Sets up the animations for the minotaur
	/// </summary>
	public override void SetupAnimations()
	{
		throw new System.NotImplementedException();
	}

}

