//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Movable 
{
	/// <summary>
	/// Move the given object the given speed
	/// </summary>
	void Move(GameTime() gameTime, int speed);

}

