//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// The player that "moves", pickups, and places things.
/// </summary>
public class Player : MoveableTile, AnimatedTile
{
	/// <summary>
	/// The number of torches the player has
	/// </summary>
	public virtual int Torches
	{
		get;
		set;
	}

	/// <summary>
	/// The number of comrades that have been rescued
	/// </summary>
	public virtual int ComradesRescued
	{
		get;
		set;
	}

	/// <summary>
	/// The number of comrades picked up but not rescued yet
	/// </summary>
	public virtual int ComradesHeld
	{
		get;
		set;
	}

	/// <summary>
	/// The animation of the player being picked up
	/// </summary>
	public virtual Animation IdleAnimation
	{
		get;
		set;
	}

	/// <summary>
	/// The animation of the player moving
	/// </summary>
	public virtual Animation MovingAnimation
	{
		get;
		set;
	}

	/// <summary>
	/// The animation of the playerpicking up a comrade
	/// </summary>
	public virtual Animation PickupAnimation
	{
		get;
		set;
	}

}

